name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  nix-flake-check:
    name: nix flake check
    runs-on: nxpkgs

    container:
      volumes:
        - /nix:/mnt/nix:ro

    steps:
      - name: Code checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: nix flake check
        run: nix flake check --all-systems
