name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  nix-flake-check:
    name: nix flake check
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Code checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@de22e16c4711fca50c816cc9081563429d1cf563 # v10

      - name: Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@fc6aaceb40b9845a02b91e059ec147e78d1b4e41 # v4

      - name: nix flake check
        run: nix flake check --all-systems
