name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  nix-flake-check:
    name: nix flake check
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Code checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@65d7c888b2778e8cf30a07a88422ccb23499bfb8 # v4

      - name: Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@53b6b26c21172d05af1bbc39e3fb6facd7140272 # v1

      - name: nix flake check
        env:
          NIXPKGS_ALLOW_UNFREE: 1
        # The `--impure` flag is required to respect `NIXPKGS_ALLOW_UNFREE`.
        run: nix flake check --impure
