name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  nix-flake-check:
    name: nix flake check
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Code checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@8cdf194da984e4f12b2f8c36d1fa107c1dd67f5c # v11

      - name: Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@fc6aaceb40b9845a02b91e059ec147e78d1b4e41 # v4

      - name: nix flake check
        run: nix flake check --all-systems
